version: "3.3"
services:
  samplefolder:
    build:
      context: ./samplefolder
      dockerfile: Dockerfile
    image: sampleimage
    container_name: samplecontainerr
    ports:
      - "3000:3000"
    restart: on-failure
