name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        server-ip: ${{ secrets.SERVER_IP }}
        server-port: ${{ secrets.SERVER_PORT }}
        remote-username: ${{ secrets.REMOTE_USERNAME }}
        docker-compose up -d

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag my-app DOCKER_USERNAME/repo:latest

    - name: Push Docker image
      run: docker push DOCKER_USERNAME/repo:latest


