---
name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USERNAME: ${{ secrets.REMOTE_USERNAME }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy with docker-compose
        run: |
          docker-compose up -d
          docker-compose pull sampleimage

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push image to Docker Hub
        run: |
          docker tag sampleimage hackerarun/sampleimage
          docker push hackerarun/sampleimage
            

