name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker build -t my-app .
        docker run my-app npm test

    - name: Push to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker tag my-app username/repo:latest
        docker push username/repo:latest

    - name: Deploy
      run: |
        # Add your deployment steps here
        echo "Deploying to production..."
