---
name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update known_hosts
        run: |+
          mkdir -p ~/.ssh
          ssh-keyscan 43.204.38.88 >> ~/.ssh/known_hosts 
            
      - name: Deploy to Server
        run: |
          sshpass -p ${{ secrets.REMOTE_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USERNAME }}@${{ secrets.SERVER_IP }} 'sudo docker-compose up -d'     

